# Generated by Django 3.2.13 on 2022-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bully', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rpwd',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
