# Generated by Django 3.2.13 on 2022-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bully', '0002_user_rpwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rpwd',
            field=models.CharField(max_length=255),
        ),
    ]
