# Generated by Django 3.2.13 on 2022-04-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bully', '0003_alter_user_rpwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='pix')),
            ],
        ),
    ]
